export type YoubikeData = {
    sno: string;
    sna: string;
    tot: number;
    sbi: number;
    sarea: string;
    mday: Date;
    lat: number;
    lng: number;
    ar: string;
    sareaen: string;
    snaen: string;
    aren: string;
    bemp: number;
    act: string;
    srcUpdateTime: Date;
    updateTime: Date;
    infoTime: Date;
    infoDate: Date;
};
